### ISSUE TITLE
Can the rosbag be provided separately?

### ISSUE THREAD

**Issue by agneevguin** [swyphcosmo/ros-camera-lidar-calibration#1]
According to my understanding, the rosbag '2016-11-22-14-32-13_test.bag' is available through the vagrant Virtual Machine. I don't have the licence to vagrant so is there a possibility to access the rosbag separately?

**Comment by dineshresearch** [comment]
please answer @swyphcosmo

**Comment by swyphcosmo** [comment]
Sorry that I didn't see the original issue from @agneevguin.

Unfortunately, I cannot provide the lyftbag that I used. This work was part of an interview assignment with a company I later worked for. auro.ai/ridecell.com. The process I used is pretty well documented. You should be able to apply it to similar datasets which contain similar camera and lidar data.
