### ISSUE TITLE
about the jenson file

### ISSUE THREAD

**Issue by ttomchy** [swyphcosmo/ros-camera-lidar-calibration#2]
thank you for providing the code of calibrate the lidar and camera. I just follow your structions. Now i am stuck in how to use the jenson file.? what the meaning of the data in the jenson file. can you explain ｍｏｒｅ　details about the jenson file.

**Comment by swyphcosmo** [comment]
I'm not sure what you mean by `jenson file`. I'm closing this issue for now. Feel free to reopen it if you can provide more information about what you're looking for.
