### ISSUE TITLE
Not able to launch "part2-cameralidar-calibration.launch" file

### ISSUE THREAD

**Issue by navinrahim** [swyphcosmo/ros-camera-lidar-calibration#3]
I have cloned the repo and following the steps provided in the read me document. Not able to run the following command. kindly post your suggestions : 

$ roslaunch launch/part2-cameralidar-calibration.launch 

error message : 
ERROR: cannot launch node of type [lidar_image_calibration/lidar_image_calibration.py]: can't locate node [lidar_image_calibration.py] in package [lidar_image_calibration]

**Comment by Jyothikumar-b** [comment]
Hi @navinrahim ,

I have also faced the similar issue. 
First check whether you have file on in the directory "scripts/lidar_image_calibration/lidar_image_calibration.py" 
Secondly, give execution access to that file
"$ chmod +x lidar_image_calibration.py"

It worked for me :+

**Comment by navinrahim** [comment]
It worked
